# Generated by Django 3.0.14 on 2022-06-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notesmaking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=30)),
                ('about_task', models.CharField(max_length=200)),
            ],
        ),
    ]
