# Generated by Django 3.0.14 on 2022-06-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesmaking',
            old_name='about_task',
            new_name='abouttask',
        ),
    ]
